#ifndef __TESTEDE_HEADER_H__
#define __TESTEDE_HEADER_H__



#endif//__TESTEDE_HEADER_H__

#ifdef TESTEDE_HEADER_IMPLEMENTATIONS
#ifndef __TESTEDE_HEADER_IMP__
#define __TESTEDE_HEADER_IMP__



#endif//__TESTEDE_HEADER_IMP__
#endif//TESTEDE_HEADER_IMPLEMENTATIONS
