
#define DEFINE_TOKEN() \
  TOKEN_VARIANT(IDENTIFIER) \
  TOKEN_VARIANT(KEYWORD) \
  TOKEN_VARIANT(COMMENT) \
  TOKEN_VARIANT(STRING) \
  TOKEN_VARIANT(NUMBER) \
  TOKEN_VARIANT(PUNCT) \
  TOKEN_VARIANT(BRACE) \
  TOKEN_VARIANT(NEWLINE) \
  TOKEN_VARIANT(INCLUDE) \
  TOKEN_VARIANT(FUNCTION) \
  TOKEN_VARIANT(SPACE) \
  

#define TOKEN_VARIANT(VARIANT) "TOKEN_"#VARIANT,
char *token_kind_name[] = {
  DEFINE_TOKEN()
};
#undef TOKEN_VARIANT


#define TOKEN_VARIANT(VARIANT) TOKEN_##VARIANT,
typedef enum {
  DEFINE_TOKEN()
} TokenKind;
#undef TOKEN_VARIANT
