name: Build and release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make -C "./C"
      id: build
      run: cd C && make -Bk && cd -
    - name: Pack
      id: pack
      run:
        mkdir clib                 |
        mv C/lib C/include clib        |
        tar czvf clib.tar.gz clib
    - name: Release
      id: create-release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        files: clib.tar.gz

    # - name: release
    #   id: create-release
    #   use: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #
    # - name: upload tar
    #   id: create-release-assets
    #   use: dwenegar/upload-release-assets@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     release_id: ${{ steps.create-release.outputs.id }}
    #     assets_path: ./clib.tar.gz





#    - name: configure
#      run: ./configure

#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
